apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-cicd-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gke-cicd-demo
  template:
    metadata:
      labels:
        app: gke-cicd-demo
    spec:
      containers:
      - name: gke-cicd-demo
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5